### ISSUE TITLE
Why RCInputFirmata send message to itself,  a little explain will be helpful

### ISSUE THREAD

**Issue by wyx2000** [git-developer/RCSwitchFirmata#3]
In RCInputFirmata, signal received in report function

void RCInputFirmata::report(){
  ....
if (receiver && receiver->available()) {
 ....
sendMessage(RCINPUT_MESSAGE, pin, 10, data, rawdataLength, (byte*) rawdata);
....

but in sendMessage, it sends the message with RCINPUT_DATA,
void RCInputFirmata::sendMessage(byte subcommand, byte pin,
 ....
  Firmata.write(START_SYSEX);
  Firmata.write(RCINPUT_DATA);
  Firmata.write(subcommand);
  Firmata.write(pin);
....

doesn't that mean the message send back to the RCInputFirmata? since RCInputFirmata is the one attached to RCINPUT_DATA.

Could someone help here? how do I capture the RCINPUT_MESSAGE and send back to my client software?

**Comment by git-developer** [comment]
> doesn't that mean the message send back to the RCInputFirmata

No. It means that a message is sent from the arduino to the host, the message type is `RCINPUT_DATA` (0x5D), the subcommand is `RCINPUT_MESSAGE` (0x41) and the pin is `10` (0xA).

The protocol is described in detail [here](https://github.com/firmata/protocol/blob/master/proposals/rcswitch-proposal.md)

> how do I capture the RCINPUT_MESSAGE and send back to my client software?

You don't have to capture a message explicitely. Make sure that 
- your rf receiver device is connected to an interrupt pin of your arduino  (e.g. pin 3)
- your arduino has the RCSwitchFirmata sketch
- you send a message to the arduino to configure the interrupt pin as rc switch receiver pin
If all this is prepared: whenever your receiver receives a signal, the `report()` method is called and the message is sent to the host

**Comment by wyx2000** [comment]
Thanks, finally figured it out. The client lib formata.js doesn't have explicitly support to RCInputFirmata, I have to write a bit more code to handle the input and output..
